using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Xml.Serialization;

// The Hash class serializes the SHA256 hash code of the course.xml file
// to prevent tampering and vandalism.
// It is generated by this authoring program but not checked here when
// loading the file.  It is checked when the file is loaded by the student version.

namespace Learning
{
    [XmlRoot]
    public class Hash{

        // The hash code.
        [XmlElement("hash")]
        public byte[] HashCode = new byte[256];
        // Methods to serialize and deserialize.
        private XmlSerializer serializer = new XmlSerializer(typeof(Hash));
        public void Serialize(string file){
            TextWriter writer = new StreamWriter(file);
            serializer.Serialize(writer, this);
            writer.Close();
        }
        public Hash Deserialize(string file){
            StreamReader reader = new StreamReader(file);
            Hash hash = (Hash)serializer.Deserialize(reader);
            reader.Close();
            return hash;
        }

    }
}
